# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test python=$TRAVIS_PYTHON_VERSION pytest python-snappy
  - conda activate test
  
# Command to run tests, e.g. python setup.py test
script: 
  - pip install -e .
  - pytest