# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
addons:
  apt:
    packages:
      - libsnappy-dev

install: 
  - pip install pytest

  
# Command to run tests, e.g. python setup.py test
script: 
  - pip install -e .
  - pytest

notifications:
  email: false