{% set name = "condastats" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e719621391750d9752a0eb3cba4240463bb0a3681ad208a23c44197e38dec2e

build:
  noarch: python
  number: 0
  entry_points:
    - condastats=condastats.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - dask >=2023.1.0,<2024.3.0
    - numpy >=1.16.5,<2.0.0
    - pandas >=1.5.0,<2.0.0
    - pip
    - pyarrow >=10.0.0,<15.0.0
    - python >=3.10
    - python-snappy
    - s3fs >=2023.1.0
  run:
    - dask >=2023.1.0,<2024.3.0
    - numpy >=1.16.5,<2.0.0
    - pandas >=1.5.0,<2.0.0
    - pyarrow >=10.0.0,<15.0.0
    - python >=3.10
    - python-snappy
    - s3fs >=2023.1.0

test:
  imports:
    - condastats
  commands:
    - condastats --help
  requires:
    - pytest

about:
  home: https://github.com/sophiamyang/condastats
  license: BSD
  license_family: BSD
  license_file: 
  summary: Conda package stats CLI
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - sophiamyang
